Allow to use system zita convolver
GrandOrgue/grandorgue pull request #1099
Opened 2022-03-24 23:50 UTC by vimpostor

I am right now creating an [Arch Linux package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=grandorgue-git&id=48868a5b5853c79b9729be64fa2ebaa2c91a349e#n30) for grandorgue, but it is frowned upon compiling and bundling libraries with applications instead of dynamically linking to system shared libraries.
All other submodules already do have an `USE_INTERNAL` switch to disable the bundled library and use a system library instead, except for the zita convolver.

This patch adds a switch for zitaconvolver, so that all libraries can be linked dynamically.

2022-03-25 17:43 UTC, oleg68 commented on CMakeLists.txt
> +else()
It would be more clear to set `ZITACONVOLVER_INCLUDE_DIRS` and `ZITACONVOLVER_LIBRARIES` to empty values here.

2022-03-25 17:46 UTC, oleg68 requested changes
Pleas add the clearing the variables

2022-03-25 17:47 UTC, oleg68 commented
@vimpostor please add an entry to CHANGELOG.md describing this change

2022-03-25 19:19 UTC, vimpostor commented
> Pleas add the clearing the variables



> @vimpostor please add an entry to CHANGELOG.md describing this change

Done

2022-03-26 13:35 UTC, oleg68 approved these changes

2022-03-26 20:42 UTC, larspalo approved these changes

2022-03-27 06:32 UTC, merged