Fixed size of the Organ Selection Dialog https://github.com/GrandOrgue/grandorgue/issues/1215
GrandOrgue/grandorgue pull request #1221
Opened 2022-10-06 17:12 UTC by oleg68

Resolves: #1215

1. Removed columns `Builder info` and `Recorded date`
2. Decreased size of the Path column
3. Made the dialog size is not depending on the data size

2022-10-06 20:27 UTC, larspalo requested changes
Shouldn't help and help images be changed to reflect this change also?

2022-10-08 19:20 UTC, oleg68 commented
> Shouldn't help and help images be changed to reflect this change also?

Indeed. I've changed the image.

2022-10-13 20:11 UTC, oleg68 commented
@larspalo @rousseldenis could you approve this PR?

2022-10-16 17:26 UTC, larspalo approved these changes

2022-10-16 17:46 UTC, rousseldenis approved these changes

2022-10-16 18:32 UTC, merged