Added r_MidiMap and r_setter member variables in some classes
GrandOrgue/grandorgue pull request #1511
Opened 2023-05-05 18:35 UTC by oleg68

This PR introduces a small optimisation.

No GO behavior should be changed

2023-05-07 19:43 UTC, larspalo requested changes
This PR crashes any sample set I tried to open/load. I attach the backtrace from gdb.
[CrashBt-1511.txt](https://github.com/GrandOrgue/grandorgue/files/11415858/CrashBt-1511.txt)

2023-05-08 10:01 UTC, oleg68 commented
@larspalo fixed

2023-05-08 13:26 UTC, larspalo commented
@oleg68 Another crash when clicking a odf divisional (the GO built in seems not to be triggering it).

[1511CrashDivisionalBt.txt](https://github.com/GrandOrgue/grandorgue/files/11421518/1511CrashDivisionalBt.txt)

2023-05-08 18:09 UTC, rousseldenis approved these changes

2023-05-08 18:31 UTC, merged