Fixed displaying light of various combination buttons https://githubcom/GrandOrgue/grandorgue/issues/1536
GrandOrgue/grandorgue pull request #1558
Opened 2023-05-31 18:38 UTC by oleg68

Resolves: #1536

GO has lots of different combination systems: ODF/Generals, Banked Generals, Frame Generals, ODF/Divisional, Banked Divisionals.

Earlier each button of each system, when is pushed, was responsible for disabling buttons in all other systems and there were gaps in this knoledge caused bugs.

This PR introduces the GOCombinationButtonSet interface for controlling combination buttons. Each subsystem implementing this interface is responsible for controlling light only of it's own buttons. GOEventHandlerList collects all such objects and GOSetter broadcasts across them all.

Now GOSetter is responsible for Banked Generals and Frame Generals (Sequencer) buttons, GODivisionalSetter - for banked dividionals, GOOrganModel - for ODF Generals and GOManual - for ODF divisionals.

All other combination light controlling code has been removed. It was in
-  GODivisionalSetter::SwitchDivisionalTo
- GOSetter::ButtonStateChanged
- GOSetter::PushGeneral
- GOSetter::UpdatePosition
- GODivisionalButtonControl::Push()

This PR also renames GOSetter::ResetDisplay to GOSetter::ResetCmbButtons and reimplements throught broadcasting (GOSetter::UpdateAllSetsButtonsLight)

2023-06-01 08:36 UTC, larspalo requested changes
Just a few comments that have typos to fix. In my tests it works beautifully. The switching between builtin divisionals and odf divisionals is seamless now. Great work with that! Some other users might complain about loosing the state of the last pushed general or setter (sequencer) combination when a divisional is pushed though. Personally I don't think it's so important that I'll object to the functionality of this PR, but if you'd like to fix this - I think that any general combination (odf, builtin, setter etc) should cancel any other combination button but the divisionals should not cancel any general type of combinations. (but the switching between the divisional types in the same division should of course remain!)

2023-06-01 08:36 UTC, larspalo commented on src/grandorgue/combinations/GODivisionalSetter.cpp
> +      // reflect the ne state of the combination buttons
reflect the **new** state

2023-06-01 08:36 UTC, larspalo commented on src/grandorgue/combinations/GODivisionalSetter.h
> +   * Ubdate all divisional buttons light.
**Update** all

2023-06-01 08:36 UTC, larspalo commented on src/grandorgue/combinations/GOSetter.h
> +   * Ubdate all setter combination buttons light.
**Update** all

2023-06-01 08:36 UTC, larspalo commented on src/grandorgue/combinations/GOSetter.h
> +   * Ubdate buttons light in all combination button set.
**Update** all

2023-06-01 08:36 UTC, larspalo commented on src/grandorgue/combinations/control/GOCombinationButtonSet.h
> +   * Ubdate light of one button.
**Update** light

2023-06-01 08:36 UTC, larspalo commented on src/grandorgue/combinations/control/GOCombinationButtonSet.h
> +   * Ubdate all combination buttons light.
**Update** all

2023-06-01 08:36 UTC, larspalo commented on src/grandorgue/model/GOOrganModel.h
> +   * Ubdate all generals buttons light.
**Update** all

2023-06-02 18:31 UTC, oleg68 commented
> I think that any general combination (odf, builtin, setter etc) should cancel any other combination button

Should  a general cancel any divisionals or not?

> but the divisionals should not cancel any general type of combinations

Now they cancel. I'll see how to remove this.

2023-06-02 19:34 UTC, larspalo approved these changes

2023-06-02 19:34 UTC, larspalo commented on src/grandorgue/combinations/GOSetter.h
> +   * Ubdate all setter combination buttons light.
Update

2023-06-05 09:05 UTC, oleg68 commented
@rousseldenis could you approve this PR?

2023-06-05 11:03 UTC, rousseldenis approved these changes

2023-06-05 11:51 UTC, merged