Always save exported combinations with UTF-8-BOM
GrandOrgue/grandorgue pull request #1821
Opened 2024-03-01 21:45 UTC by nanoufo

Resolved issue #1818.
The problem occurred due to the utilization of the default system encoding for conversions between wxString and strings in YAML. yaml-cpp treats strings as a sequence of bytes and does not perform encoding conversions.

Now UTF-8 encoding is used for conversions. The exported file now begins with a UTF-8 BOM mark.
The UTF-8 BOM mark is used to differentiate documents exported from older GO versions (which use UTF-8 without BOM on Linux/Mac and one of the one-byte encodings on Windows) and to indicate to text editors to use UTF-8 encoding.

While this change has not been tested on Windows yet, it is expected to function properly.

2024-03-02 17:14 UTC, oleg68 requested changes

2024-03-02 17:14 UTC, oleg68 commented on src/grandorgue/GOOrganController.cpp
> +static std::vector<char> loadFileBytes(const wxString &file) {
```suggestion
static std::vector<char> load_file_bytes(const wxString &fileName) {
```
due the GO naming conventions about out-of-class functions

2024-03-02 17:14 UTC, oleg68 commented on src/grandorgue/GOOrganController.cpp
> +    throw wxString::Format(_("Failed to open '%s'"), file);
We need a more detailed error message: why?

2024-03-02 17:14 UTC, oleg68 commented on src/grandorgue/GOOrganController.cpp
> +    throw wxString::Format(_("Failed to read '%s'"), file);
More detailed error message is needed

2024-03-02 17:14 UTC, oleg68 commented on src/grandorgue/GOOrganController.cpp
> +  std::array<char, 3> utf8bom = {'\xEF', '\xBB', '\xBF'};
Could you make a single constant and share it with line 647?

2024-03-02 17:14 UTC, oleg68 commented on src/grandorgue/GOOrganController.cpp
> +    && std::equal(utf8bom.begin(), utf8bom.end(), content.begin())) {
If the file contains soma another BOM (not utf8), this method tries to use *wxConvCurrent instead of wxConvAuto()

2024-03-02 17:14 UTC, oleg68 commented on src/grandorgue/GOOrganController.cpp
> +static wxString loadFileTextWithEncodingDetection(const wxString &file) {
```suggestion
static wxString load_file_text_with_encoding_detection(const wxString &fileName) {
```

2024-03-04 17:41 UTC, oleg68 requested changes

2024-03-04 18:37 UTC, oleg68 approved these changes

2024-03-05 07:15 UTC, rousseldenis approved these changes

2024-03-05 07:43 UTC, merged