Added Midi event trigger for panic button and File/Exit menu
GrandOrgue/grandorgue pull request #1909
Opened 2024-05-09 19:58 UTC by lupushortus

Setter class has two new virtual buttons, that provide MIDI access to panic button and exit function
Implements Issues #1905 and #1807

2024-05-12 17:36 UTC, oleg68 requested changes

2024-05-12 17:36 UTC, oleg68 commented on src/grandorgue/combinations/GOSetter.cpp
> +  m_buttons[ID_SETTER_FILE_EXIT]->SetPreconfigIndex(25);
```suggestion
  m_buttons[ID_SETTER_FILE_EXIT]->SetPreconfigIndex(26);
```

2024-05-12 17:45 UTC, oleg68 commented
@lupushortus 

1. Please remove any changes from the `submodules/RtAudio` submodule. They do not relate to this functionality.
2. How a user can assign MIDI settings to these hidden buttons?

2024-05-14 18:22 UTC, lupushortus commented
Hi @oleg68,

1.  I struggled merging/updating upstream branch into my fork/branch handling the submodule RtAudio correctly. After some forced pushes I integrated it cleanly. Sorry for the confusion.

2. Regarding the hidden buttons: Go to menu Audio/Midi => MIDI Objects, there's a list of all MIDI elements available, search and select button Panic or Exit GrandOrgue, that appear with that change and press Configure button. Standard MIDI config dialogue will appear.

2024-05-16 13:14 UTC, oleg68 approved these changes

2024-05-16 13:15 UTC, oleg68 requested changes
@lupushortus Could you add a changelog entry and a sescriprion of new setter elements to the help file?

2024-05-16 19:39 UTC, lupushortus commented
> @lupushortus Could you add a changelog entry and a sescriprion of new setter elements to the help file?

Done

2024-05-17 05:38 UTC, oleg68 commented
@lupushortus please add also the descriprion of Exit and of the new setter elements in the `Setter elements` section

2024-05-17 05:39 UTC, oleg68 requested changes
@lupushortus please add also the descriprion of Exit and of the new setter elements in the Setter elements section

2024-05-17 09:43 UTC, lupushortus commented
> @lupushortus please add also the descriprion of Exit and of the new setter elements in the Setter elements section

Done, also added links to relevant items.

2024-05-17 14:06 UTC, oleg68 approved these changes

2024-05-22 19:06 UTC, larspalo approved these changes

2024-05-23 19:05 UTC, merged