Fixed not sounding of pipe after an enclosure has closed to zero and then opened https://github.com/GrandOrgue/grandorgue/issues/1813
GrandOrgue/grandorgue pull request #1910
Opened 2024-05-13 19:04 UTC by oleg68

Resolves: #1813

For fixing the issue I completelly reworked the `GOSoundFader` class. Earlier it calculated only the total volue that was depending on the enclosure volume. So it was not feasible to differentiate between finishing the decay and setting enclosure volume to 0. 

Now `GOSoundFader` calculates two volumes: target volume and external volume. `GOSoundFader::IsSilent()` takes into account only fade of the target volume, but not the external volume.

2024-05-22 20:21 UTC, larspalo commented
@oleg68 It seems to be working fine. There are a few un-important spelling mistakes in the comments though. However, more important, since long all the enclosures on the built in (floating and volume) panel would have the default AmpMinLevel of 1 in the Init of /src/grandorgue/model/GOEnclosure.cpp file to take into account the previous behaviour (of killing the sound at an amplitude of 0). Since this PR changes that behaviour it might be appropriate to also change the amp min level of the built in volume controls in the Init to reflect this change?

2024-05-22 20:44 UTC, larspalo requested changes

2024-05-22 20:44 UTC, larspalo commented on src/grandorgue/sound/GOSoundFader.h
> + * - Target volume. It is defined by total capacity of the asmple size and may
* - Target volume. It is defined by total capacity of the sample size and may

2024-05-22 20:44 UTC, larspalo commented on src/grandorgue/sound/GOSoundFader.h
> + * There are three staging of playing one sample related to the target volume:
* There are three stages of playing one sample related to the target volume:

2024-05-22 20:44 UTC, larspalo commented on src/grandorgue/sound/GOSoundFader.h
> + * - Decreasing: from m_СurrentVolume to 0. It is used for bothe crossfade from
* - Decreasing: from m_СurrentVolume to 0. It is used for both the crossfade from

2024-05-22 20:44 UTC, larspalo commented on src/grandorgue/sound/GOSoundFader.h
> +   * Setup the fadef for constant volume of for increasing from 0 to
* Setup the fades for constant volume or for increasing from 0 to

2024-05-22 20:44 UTC, larspalo commented on src/grandorgue/sound/GOSoundFader.h
> +    // may be m_TargetVolume has not yet been reached, but the velocity of
// maybe m_TargetVolume has not yet been reached, but the velocity of

2024-05-22 20:44 UTC, larspalo commented on src/grandorgue/sound/GOSoundFader.h
> + * This class is responsible of smooth changing a volume of samples.
* This class is responsible for smooth changing the volume of samples.

2024-05-25 13:40 UTC, oleg68 commented
@larspalo I changed the min level of internal enclosures to 0

2024-05-25 18:18 UTC, larspalo approved these changes
Seems to be working as it should.

2024-05-28 19:22 UTC, oleg68 commented
@rousseldenis Could you approve this PR?

2024-05-29 16:17 UTC, rousseldenis approved these changes

2024-05-29 16:59 UTC, merged