Renamed GOPath functions and the file
GrandOrgue/grandorgue pull request #1998
Opened 2024-09-03 06:40 UTC by oleg68

As discusses in #1991, instead of renaming one function, this PR renames all the global functions in the GOPath file according to the current GO naming convention.

It also renames the GOPath files themself.

It is just renaming. No GO behavior should be changed.

2024-09-03 09:26 UTC, larspalo requested changes
I still think that "sync" is a better option as a word than "synch" - which rather should have been "synchronize" but that's perhaps too long.

2024-09-03 09:26 UTC, larspalo commented on src/core/go_path.cpp
> +void go_synch_directory(const wxString &path) {
```suggestion
void go_sync_directory(const wxString &path) {
```

2024-09-03 09:26 UTC, larspalo commented on src/core/go_path.cpp
> +  go_synch_directory(name.GetPath());
```suggestion
  go_sync_directory(name.GetPath());
```

2024-09-03 09:26 UTC, larspalo commented on src/core/go_path.h
> +void go_synch_directory(const wxString &path);
```suggestion
void go_sync_directory(const wxString &path);
```

2024-09-03 09:26 UTC, larspalo commented on src/grandorgue/GOAudioRecorder.cpp
> +    go_synch_directory(name.GetPath());
```suggestion
    go_sync_directory(name.GetPath());
```

2024-09-03 09:26 UTC, larspalo commented on src/grandorgue/midi/GOMidiRecorder.cpp
> +    go_synch_directory(name.GetPath());
```suggestion
    go_sync_directory(name.GetPath());
```

2024-09-03 09:26 UTC, larspalo commented on src/grandorgue/GOFrame.cpp
> +  go_synch_directory(filepath.GetPath());
```suggestion
  go_sync_directory(filepath.GetPath());
```

2024-09-03 19:50 UTC, oleg68 commented on src/core/go_path.cpp
> +void go_synch_directory(const wxString &path) {
Done

2024-09-03 19:51 UTC, oleg68 commented on src/core/go_path.h
> +void go_synch_directory(const wxString &path);
Done

2024-09-03 19:51 UTC, oleg68 commented on src/grandorgue/midi/GOMidiRecorder.cpp
> +    go_synch_directory(name.GetPath());
Done

2024-09-03 19:51 UTC, oleg68 commented on src/grandorgue/GOFrame.cpp
> +  go_synch_directory(filepath.GetPath());
Done

2024-09-03 19:51 UTC, oleg68 commented on src/grandorgue/GOAudioRecorder.cpp
> +    go_synch_directory(name.GetPath());
Done

2024-09-03 19:51 UTC, oleg68 commented on src/core/go_path.cpp
> +  go_synch_directory(name.GetPath());
Done

2024-09-17 19:15 UTC, oleg68 commented
@rousseldenis could you approve this PR?

2024-09-18 12:41 UTC, rousseldenis approved these changes

2024-09-18 17:48 UTC, merged