Added upgrade and uninstall guide to INSTALL.md
GrandOrgue/grandorgue pull request #749
Opened 2021-10-01 20:04 UTC by oleg68

Resolves: #720

2021-10-01 20:11 UTC, larspalo requested changes
A few spelling mistakes should perhaps be fixed.

Line 4: general, upgrading
Line 89: already

2021-10-02 06:51 UTC, Jean-Gabriel1982 submitted a review, later dismissed

2021-10-02 09:06 UTC, rousseldenis requested changes
Some comments

2021-10-02 09:06 UTC, rousseldenis commented on INSTALL.md
> +2. Install the downloaded files or upgrade existing installation with this file. This step is operation system dependent.
```suggestion
2. Install the downloaded file or upgrade existing installation with this file. This step is operation system dependent.
```

2021-10-02 09:06 UTC, rousseldenis commented on INSTALL.md
> +## Attention
```suggestion
## Warning
```

2021-10-02 09:06 UTC, rousseldenis commented on INSTALL.md
> +Installation of program creates neither the configuration file nor directories used by GrandOrgue to store data and cache. These directories are reside in the user home directory and are created when
```suggestion
Installation of program creates neither the configuration file nor directories used by GrandOrgue to store data and cache. These directories reside in the user home directory and are created when GrandOrgue is launched the first time.
```

2021-10-02 09:06 UTC, rousseldenis commented on INSTALL.md
> +This method requires that all dependencies have already been installed. Usually this way is used for trying a new GrandOrgue version when an old one has alreade been installed.
```suggestion
This method requires that all dependencies have already been installed. Usually this way is used for trying a new GrandOrgue version when an old one has already been installed.
```

2021-10-02 09:06 UTC, rousseldenis commented on INSTALL.md
> +## Attention
```suggestion
## Warning
```

2021-10-02 17:16 UTC, oleg68 commented
Thanks, @larspalo and @rousseldenis. I've made all suggesed changes.

2021-10-02 17:48 UTC, larspalo approved these changes

2021-10-02 18:43 UTC, Jean-Gabriel1982 approved these changes

2021-10-04 06:53 UTC, oleg68 commented
@rousseldenis could you check this PR?

2021-10-04 07:10 UTC, rousseldenis approved these changes

2021-10-04 07:26 UTC, merged