PortAudio Library Upgraded to Latest Stable Release, v19.7.0.
GrandOrgue/grandorgue pull request #801
Opened 2021-10-25 23:53 UTC by pgcrowe

This pull upgrades the PortAudio Library to the latest stable release, v19.7.0. [http://files.portaudio.com/download.html](http://files.portaudio.com/download.html) This upgrade fixes the PortAudio driver errors occurring in GrandOrgue on macOS 11. **NOTE: Build was successful on macOS 11. However, testing is needed on Linux and Windows before the commit is approved. If any others developers would be so kind as to test on those platforms, I would appreciate it.**

2021-11-03 15:57 UTC, pgcrowe commented
@oleg68: My apologies for my delay on updates to this commit. I've been inundated with work this past week. I'll try to continue debugging later this week. In the meantime, feel free to make changes as you see fit.

2021-11-03 16:08 UTC, pgcrowe commented on src/portaudio/CMakeLists.txt
> +  src/common/pa_allocation.c
I tried {CMAKE_SOURCE_DIR} a few commits ago, and it didn't work for some reason. I'll try again, I may have been lacking the $ or something.

2021-11-03 18:47 UTC, oleg68 commented on .gitmodules
> +	url = https://github.com/PortAudio/portaudio.git
Please fix the submodule to the latest release tag

2021-11-03 18:51 UTC, oleg68 requested changes
It stiil needs to add subdirectory src/portaudio instead of submodules

2021-11-08 20:04 UTC, oleg68 commented
@pgcrowe I've pushed a PR https://github.com/pgcrowe/grandorgue/pull/1 to your fork with suggested changes.

2021-11-11 16:05 UTC, oleg68 requested changes
Everything looks OK, but resolve the conflicts, please

2021-11-11 16:06 UTC, oleg68 requested changes
Resolving conflicts is required

2021-11-11 19:15 UTC, oleg68 commented
@pgcrowe resolving conflicts in configurations.xml is hard, so just take the new version from upstream.

2021-11-13 11:32 UTC, oleg68 commented
@pgcrowe Because you haven't fix your PR, I've created another one with your commits: #845

2021-11-13 11:32 UTC, closed without merging