Fixed a bug in .cmb reading from an organ in a package
GrandOrgue/grandorgue pull request #814
Opened 2021-10-30 12:32 UTC by larspalo

Resolves #813

2021-10-30 14:49 UTC, oleg68 requested changes

2021-10-30 14:50 UTC, oleg68 commented
I've tested 4.4.1-0.15 from your repo. Seems it works. Only please remove the changelog.

2021-10-30 16:16 UTC, oleg68 approved these changes

2021-10-31 09:16 UTC, rousseldenis approved these changes

2021-10-31 09:55 UTC, merged