Fixed crash under OSx when closing a MIDI event dialog
GrandOrgue/grandorgue pull request #971
Opened 2022-01-17 19:48 UTC by oleg68

Resolves: #966

2022-01-17 20:21 UTC, larspalo requested changes
In MIDIEventDialog.cpp there's two different stylings of similar if / else statements. Compare lines 80-83 and 87-90. I know it has no practical importance, but maybe we should have a single styling for the single line if/else statements.

2022-01-18 07:10 UTC, oleg68 commented
> In MIDIEventDialog.cpp there's two different stylings of similar if / else statements. Compare lines 80-83 and 87-90. I know it has no practical importance, but maybe we should have a single styling for the single line if/else statements.

Fixed

2022-01-18 09:51 UTC, larspalo approved these changes

2022-01-18 10:02 UTC, rousseldenis approved these changes

2022-01-18 11:31 UTC, merged