Update fr.po
GrandOrgue/grandorgue pull request #977
Opened 2022-01-19 11:15 UTC by Jean-Gabriel1982

2022-01-19 11:38 UTC, oleg68 commented on po/fr.po
>  msgid "Reverb"
I suggest you to change the order of the msgid for reflecting the tab order in the dialog.

2022-01-19 11:39 UTC, oleg68 commented on po/fr.po
> +msgstr "Config.MIDI initiale"
Very long. For avoiding OSx issues with wrapping.

```suggestion
msgstr "MIDI initiale"
```

2022-01-19 12:17 UTC, oleg68 approved these changes

2022-01-19 13:59 UTC, oleg68 requested changes
@Jean-Gabriel1982 please add an entry to the CHANGELOG.md describing your changes

2022-01-21 20:49 UTC, larspalo commented
@oleg68 Please, updating translation is not introducing anything noteworthy so there's really no need to add a CHANGELOG entry for that. It's another thing if a new language is added.

2022-01-24 18:36 UTC, rousseldenis commented
> @oleg68 Please, updating translation is not introducing anything noteworthy so there's really no need to add a CHANGELOG entry for that. It's another thing if a new language is added.

I agree.

Thinking about it, we could imagine an external translation service such as weblate. That allows external contributors to translate the software. https://weblate.org/fr/

2022-01-24 18:36 UTC, rousseldenis approved these changes

2022-01-24 20:13 UTC, oleg68 commented
@Jean-Gabriel1982 Based on your PR I've made a new one: #986 whith adding in French all untranslated items in the settings dialog

2022-01-24 20:13 UTC, closed without merging